### PR TITLE
Allow version 3 of symfony components

### PR DESCRIPTION
**Pull request by temp**
Allow versions 3.x.y of symfony components.

composer update; vendor/bin/phpunit => all green
composer update --prefer-lowest; vendor/bin/phpunit => all green

### CODE REVIEW

**Comment by temp** [comment]
Since travis/composer/php-5.3.3 seems to be broken, how relevant is this failing branch?

**Comment by fabre-thibaud** [comment]
Its relevant as long as PHP 5.3.3 is marked as supported in the composer.json file... but I'm not against dropping support for EOL'ed PHP versions, however that will require a major version release since we are trying to stick to semver. But thanks for your work, I'll merge it once I've had the timd to review it

**Comment by temp** [comment]
Any news on this one?

**Comment by fabre-thibaud** [comment]
I merged your P/R and it is available as 0.6.0 (due to dropping support for 5.3 and 5.4). Thanks for your contribution :)

**Pull request merged**
